name: Build and Test

on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_PLATFORM: x64

jobs:
  build-and-test:
    name: MSBuild + XUnit
    runs-on: windows-2022
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[17.0,)'
        msbuild-architecture: x64

    - name: Configure VCPKG dependencies
      run: |
        bootstrap-vcpkg
        vcpkg install box2d:x64-windows
        vcpkg integrate install

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}

    - name: Unit Tests
      run: dotnet test /p:Configuration=${{matrix.BUILD_CONFIGURATION}} ./test/UnitTests/UnitTests.csproj
